export const PATH = {
  LOGIN: 'auth/signin',
  SIGN_UP: 'users/signup',
  LABELS: 'label',
  TOPICS: 'topic',
  ASKED: 'asked',
  SIGN_IN_WITH_GOOGLE: 'auth/google',
  INVITE_USERS: 'invites',
  REFRESH_TOKEN: 'auth/refresh',
  LIKE_TOGGLE: 'likes/toggle',
  SEARCH: 'search?keyword=',
  GET_USER_BY_ID: 'users/user',
  CONTENTS: 'content',
  LIST_ALL_ROLES:'role/list',
  ROLES: 'role',
  CREATE_ROLE: 'role/create',
  TENANTS: 'tenant',
  TENANT_CREATE: 'tenant/create',
  TENANT_SEARCH: 'tenant?',
  USER_UPDATE: 'users?id=',
  FILTER_ROLE: 'role/search?',
  ROLES_WITH_PAGINATION: 'role/list',
  USER_PATH: 'users',
  USER_SEARCH: 'users?',
};
